### ISSUE TITLE
"designToDescriptives()" --> "HajekEstimates()"; ...

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/RItools#100]
(The point being less to change the name than to reorient and generalize the function.   E.g., it may be that `designToDescriptives()` gets a name other than `HajekEstimates()` in order to reserve that name for a user-facing version calling the current `designToDescriptives`.  But even if the name doesn't change at least a couple adjustments, to functionality and/or signature will be appropriate; for now I'm recording ideas about which in the comments below.)

**Comment by benthestatistician** [comment]
Related proposal that I'd like to file under this project, but noting here for potential discussion first:  As things stand there's code within `designToDescriptives()` that identifies strata without both treatment and control groups represented, then kicks them out. I believe I suggested this, and that the purpose was back-compatibility with `xBalance()`.  But I now think it's a mistake; rather I'd want the natural behavior of a Hajek estimator, which doesn't concern itself with equal representation by strata. 

Here are some results from some calculations I've been doing on an applied project, as illustration of why the current `designToDescriptives()` kickout policy is unnatural. First, a calculation of differential attrition, with weighting for school size and for the reciprocal of a priori probability of assignment to the treatment group. 

```r
coef(lm(attritor ~ Tx, weights=iprob*Total.KG.to.G03))
## (Intercept)      TxTRUE 
##      0.4777     -0.0151
```

Now `balT()`'s calculation of much the same thing. 

```r
balanceTest(Tx~ attritor + strata(thematch)-1, 
unit.weights=Total.KG.to.G03, data=base_ra, 
report=mean_stats)
##          strata():  thematch                         
##          stat      Treatment Control adj.diff       z
## vars                                                 
## attritor             0.45    0.46     -0.0074 -1
```

Notice how not the same.  The main source of the difference being a single matched pair in which one school, the one assigned to control, attritted, while the other stayed.  The stayer in that pair gets removed from the `balT()` calculation.  Looking at it in the bright light of day, I think it's weird and should be reverted.

**Comment by markmfredrickson** [comment]
I'm trying to set up a [reproducible example of this problem](https://github.com/markmfredrickson/RItools/blob/issue-100/tests/testthat/test.balanceTest.R#L36), but I'm not able to create an example that fails. What exactly is NA'd in the example data?

**Comment by benthestatistician** [comment]
I may have miscommunicated: it's not that some set of Xs receive NAs (as you wrote [here](
https://github.com/markmfredrickson/RItools/blob/issue-100/tests/testthat/test.balanceTest.R#L47)), rather that one or more clusters that were present at the time of random assignment are not represented in the `data` as provided to `balT()`, with the result that it looks to `balT()` as though there is a stratum with members of the treatment group but not members of the control group.  I.e., the `makeDesigns()` warning at [Design.R#L318](
https://github.com/markmfredrickson/RItools/blob/issue-100/R/Design.R#L318) has been triggered.

**Comment by markmfredrickson** [comment]
Ok. I've updated my test case to list-wise delete all of the treated in a particular stratum. 

Should "n"s be computed using sums of weights rather than actual unit counts? Particularly, I'm looking at [this function](https://github.com/markmfredrickson/RItools/blob/master/R/Design.R#L854). I can give it a try to see if the results line up with the `lm` equivalents, but I figured I'd ask as well.

**Comment by markmfredrickson** [comment]
I've got most of the fixes we discussed in place and a set of tests in place.

When all subjects in a design are available, `lm` and `balanceTest` agree. When subjects are lost to follow up, they do not. I think the issues that `balanceTest` attempts to infer the probability of treatment assignment from the observed numbers of treated and control units. Consequently, when observations are missing, we're setting incorrect treatment assignment probabilities for subjects in those strata.

In [test.balanceTest.R](https://github.com/markmfredrickson/RItools/blob/issue-100/tests/testthat/test.balanceTest.R#L87), I thought setting the weight to zero for `lm` would generate a result equivalent to balance. Instead, the closest weighting I can find is about 28.5 for the single observation in its own stratum. I'm not quite sure where this value comes from.

**Comment by markmfredrickson** [comment]
(The following is mostly a note to myself). Even with zeroing out individual units, it seems like we can get the wrong strata weights.

**Comment by benthestatistician** [comment]
(That would explain something I saw in a calculation just now: unexpectedly large changes to z and chi-square statistics as I added in an additional pair of clusters as a stratum, where one of the clusters was a zero-weight placeholder.  So I'll be following this with interest.  I could also take a look at the weights for my last stratum, if might be helpful.)

**Comment by benthestatistician** [comment]
I checked in my example for funny strata weights.  In that example the strata weights seem OK, but alignment isn't doing what I had thought it would do, namely making it the case that the additional stratum doesn't wind up making a contribution to the inferential statistics.  (It does make a contribution, counter to my earlier expectation.)

In the example I "completed" a pair in which one but not the other of the clusters had attritted from the study.  The attritting cluster, "`TFOA`", was not represented in my data set, so for it I added a row, with NA for each x observation, and with 0 unit weight.  The other cluster ("`OMAR`") was represented in the original data set with a number of positive weight, non-NA observations. 

I expected that alignment within strata would have the effect of turning `OMAR`'s x-values into 0s and `TFOA`'s into non-zero numbers; this because the (appropriately weighted) stratum means should be determined entirely by `OMAR` values.  If the aligned `TFOA` values are then weighted as 0s while `OMAR` is given positive weight, then both wind up contributing 0; or so I thought.  Instead I got:

```r
Browse[2]> which(strataAligned$jn_match@Cluster=="OMAR")
 [1] 16
 Browse[2]> which(strataAligned$jn_match@Cluster=="TFOA")
 [1] 1
!Browse[2]> strataAligned$jn_match@Covariates[c(1,16),]
      n_boy_dibels0 n_boy_dibels1 n_boy_dibels2+ (_any Xs recorded_)
 [1,]        0.0389       -0.0326       -0.00631                   0
 [2,]       -0.0329        0.0276        0.00533                   0
```

Even if it had worked as I was expecting, I'm not sure everything would be as it should; in particular, the inferential calculations will need to explicitly drop strata of this type, where one or the other condition has 0 weight associated with it, if we wish to maintain equivalency between our adjusted means differences and the treatment coefficient of a regression with fixed effects for strata.   Although stratum weights might play a role in effecting this, in my example i'm not seeing anything too odd in the stratum weight attaching to the anomalous stratum.

**Comment by benthestatistician** [comment]
After fixing an unrelated bug (bb4c29c , 1eed98d; introduced by me in attending to #99),  the `TFOA`/`OMAR` pair discussed in my last post now contributes nothing to the inferential calculations, consonant with my earlier expectations:
```r
tmat[c(36,46),]
      n_boy_dibels0 n_boy_dibels1 n_boy_dibels2+ (_any Xs recorded_)
 [1,]             0             0              0            4.88e-18
 [2,]             0             0              0            0.00e+00
```
(Stratum weights for this pair look OK also.)

**Comment by markmfredrickson** [comment]
Feel free to check your examples on the master branch. I think I've got this one buttoned up.

**Comment by benthestatistician** [comment]
Thanks, Mark!
