### ISSUE TITLE
Maintenance release

### ISSUE THREAD

**Issue by markmfredrickson** [markmfredrickson/RItools#104]
We've got a few changes that are worth a maintenance release, even if some of the bigger projects aren't yet ready for general release. Tasks:

- [ ] Identify last release commit
- [ ] Identify changes to master that should be move to a branch
- [ ] Any branches that include features that should be in a release?
- [ ] Double check that the NEWS file has proper fixes listed.
- [ ] Usual release quality assurance process

**Comment by benthestatistician** [comment]
out of date, closing
