### ISSUE TITLE
CI for branches

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/RItools#120]
We should have continuous integration testing for the proj1-balT branch as well as master.

**Comment by benthestatistician** [comment]
Josh, if you'd be willing to set this up I'd be very grateful. Alternatively you could point me in the direction of how to do it. (E.g., is it a matter of copying the material you have in .github/workflows on the master branch over the the proj1-balT branch, perhaps after adaptation, or is it a matter of adjusting that material within the master branch?)

**Comment by josherrickson** [comment]
Done. Gonna cause one more conflict when master/proj1-balT are merged, but at least this one should be straightforward.

**Comment by josherrickson** [comment]
For the record, it was what you suggested; move over the yml file and add the branch.

The failure we're seeing is due to RSVGTipsDevice which has been removed from CRAN (https://cran.r-project.org/web/packages/RSVGTipsDevice/index.html). I think when the master branch gets re-CI'd, it will fail as well. We probably need to remove that dependency.

**Comment by benthestatistician** [comment]
Thanks very much for this, Josh!  

We're keeping the RSVGTipsDevice code around to avoid breaking stuff in MEERKT. 

This doesn't mean we have to include it in the public release of the package, of course.  In 1306735 on the proj1-balT branch I move the pertinent tests to test.notforCRAN.R, a first step.  In proj1-balT 256faab, the signature of `RItools:::balanceplot()` changes a little in order to allow us to feed in a plotting function that makes use of RSVGTipsDevice, if we so choose, while removing reverences to that package from the version of our package that goes to CRAN. Hopefully this will do the trick.  If you have comments on this solution, do share.
