### ISSUE TITLE
Unable to install optmatch due to missing RItools dependency

### ISSUE THREAD

**Issue by riazgillani** [markmfredrickson/RItools#123]
Hello - I am receiving the following error when I try to install the optmatch package: “dependency ‘RItools’ is not available”

I notice that RItools has been removed from the CRAN repository: https://cran.r-project.org/web/packages/RItools/index.html

Will RItools be made available again? Is there a workaround to enable the use of optmatch in the mean time?

Thanks,
Riaz

**Comment by josherrickson** [comment]
Sorry for the inconvenience. 
We've submitted an update and hope that it should be up shortly. In the meantime you can install the developer version by following the instructions here: https://github.com/markmfredrickson/RItools#using-a-development-version-of-ritools
