### ISSUE TITLE
Fix problems with our testing suite

### ISSUE THREAD

**Issue by jwbowers** [markmfredrickson/RItools#126]
From Prof. Ripley this morning:

On 22/07/2022 08:08, Prof Brian Ripley wrote:
> Dear maintainer,
> 
> Please see the problems shown on
> <https://cran.r-project.org/web/checks/check_results_RItools.html >.
> 
> Please correct before 2022-08-08 to safely retain your package on CRAN.
> 
> Do remember to look at the 'Additional issues'.
> 
> The CRAN Team

Your test obfuscation suite does not even tell us what the warnings were!

-- 
Brian D. Ripley,                  [ripley@stats.ox.ac.uk](mailto:ripley@stats.ox.ac.uk)
Emeritus Professor of Applied Statistics, University of Oxford

**Comment by josherrickson** [comment]
For this one:

> Version: 0.3-0
Check: whether package can be installed
Result: ERROR
    Installation failed.
Flavor: [r-oldrel-windows-ix86+x86_64](https://www.r-project.org/nosvn/R.check/r-oldrel-windows-ix86+x86_64/RItools-00check.html)

it looks like it may be an issue on their end? https://www.r-project.org/nosvn/R.check/r-oldrel-windows-ix86+x86_64/RItools-00install.html shows 

> Error: package or namespace load failed for 'ggplot2' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called 'pillar'

but there clearly is: https://cran.r-project.org/web/packages/pillar/index.html

**Comment by josherrickson** [comment]
The "ATLAS" thing is new to me. Clicking through, we get:

>   ══ Skipped tests ════
  • empty test (4)
>  ══ Failed tests ═══
  ── Failure (test.Design.R:1130:3): HB08 and HB08_2016 flag degenerate statistics ──
  `balanceTest(z ~ . + strata(b), data = df_good, inferentials.calculator = RItools:::HB08)` produced warnings.
  ── Failure (test.Design.R:1131:3): HB08 and HB08_2016 flag degenerate statistics ──
  `balanceTest(z ~ . + strata(b), data = df_good, inferentials.calculator = RItools:::HB08_2016)` produced warnings.

Seems pretty easy to fix; eliminate those empty tests (or add something trivial like `expect_true(TRUE)` if they accomplish something), and wrap those other two lines in `expect_warning()`.

**Comment by jwbowers** [comment]
Thanks so much for jumping on this @josherrickson ! I was also confused by the last comment about "test obfuscation suite".

**Comment by benthestatistician** [comment]
At least some of this is my bad.  Sorry guys, and thanks for the help!

> Your test obfuscation suite does not even tell us what the warnings were!
> ...
> Emeritus Professor...

Sigh.

**Comment by josherrickson** [comment]
Those "produced warnings" tests aren't producing the warnings on my end. I think it may be in some specific scenario. https://www.stats.ox.ac.uk/pub/bdr/Rblas/README.txt Suggests that ATLAS is a specific set of libraries, so if we wrap those tests in an `expect_warning()`, it'll fail on all other systems. I'd suggest moving those two particular tests (e.g. the entire `test_that()`) into the `test.notforCRAN` file.

**Comment by josherrickson** [comment]
> 



> For this one:
> 
> > Version: 0.3-0
> > Check: whether package can be installed
> > Result: ERROR
> > Installation failed.
> > Flavor: [r-oldrel-windows-ix86+x86_64](https://www.r-project.org/nosvn/R.check/r-oldrel-windows-ix86+x86_64/RItools-00check.html)
> 
> it looks like it may be an issue on their end? https://www.r-project.org/nosvn/R.check/r-oldrel-windows-ix86+x86_64/RItools-00install.html shows
> 
> > Error: package or namespace load failed for 'ggplot2' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
> > there is no package called 'pillar'
> 
> but there clearly is: https://cran.r-project.org/web/packages/pillar/index.html

This error no longer appears on the page, so all that is needed is to move those few tests into not-for-CRAN.

**Comment by markmfredrickson** [comment]
I've reorganized the end of that test to make it easy to add a "skip_on_cran()" to avoid just the two failing tests. I'm running it through winbuilder right now.

**Comment by markmfredrickson** [comment]
Just to close the loop, the winbuilder results were good, so this release is ready to get a version number bump and a release.

**Comment by josherrickson** [comment]
@markmfredrickson Sorry to be nosy, but I don't see any commit moving the tests into a not-for-cran status?

**Comment by markmfredrickson** [comment]
Oops! Changes pushed: e797f9f437d824f50efdda620822b1925587bb83

**Comment by jwbowers** [comment]
Submitted commit 7f9f2ba82c415ea15d7894536128167d72001fec . Closing this issue. Thanks y'all!

**Comment by jwbowers** [comment]
Reopening this: 

On 07.08.2022 19:20, Bowers, Jacob W wrote:
> Dear Professor Ripley and CRAN Team,
> 
> We have fixed those errors that were arising from our local test suite running on ATLAS based systems. We are using the testthat::skip_on_cran() approach. Since we don�t have access to a system using ATLAS, and didn�t see such a system on rhub, we hope that this resubmission works on the ATLAS-based test system that y�all are using on CRAN.

Ummm, that means now you are hiding the differences seen previously?
On ATLAS we have seen

Running the tests in ‘tests/testthat.R’ failed.
Complete output:
   > library(testthat)
   > library(RItools)
   Loading required package: ggplot2
   >
   > test_check("RItools")
   [ FAIL 2 | WARN 1 | SKIP 4 | PASS 1427 ]

   ══ Skipped tests 
═══════════════════════════════════════════════════════════════
   • empty test (4)

   ══ Failed tests 
════════════════════════════════════════════════════════════════
   ── Failure (test.Design.R:1130:3): HB08 and HB08_2016 flag degenerate 
statistics ──
   `balanceTest(z ~ . + strata(b), data = df_good, 
inferentials.calculator = RItools:::HB08)` produced warnings.
   ── Failure (test.Design.R:1131:3): HB08 and HB08_2016 flag degenerate 
statistics ──
   `balanceTest(z ~ . + strata(b), data = df_good, 
inferentials.calculator = RItools:::HB08_2016)` produced warnings.


which is of course maximally unhelpful to know what and how servere the 
issue is (no surprise given you used the testthat test obfuscation 
tools). Hiding issues does not solve them: users on ATLAS platforms will 
experience these issues...

Best,
Uwe Ligges





> Thanks much for finding this error for us!
> 
> Best
> 
> Jake
> 
> Jake Bowers
> Dept of Political Science and Statistics
> https://urldefense.com/v3/__http://jakebowers.org__;!!DZ3fjg!-QbMoeOn2hFKchTNuUVDYB86FeDAaMKpRvNva6dJB-V-CQWXLEgrW1yKSvvcC8rVp46-evYxkuDD5dTx8YWyhS12J7i4TzCA$ 
> 
> 
> From: Prof Brian Ripley <[ripley@stats.ox.ac.uk](mailto:ripley@stats.ox.ac.uk)>
> Date: Friday, July 22, 2022 at 03:12
> To: Bowers, Jacob W <[jwbowers@illinois.edu](mailto:jwbowers@illinois.edu)>
> Cc: [CRAN@R-project.org](mailto:CRAN@R-project.org) <[CRAN@R-project.org](mailto:CRAN@R-project.org)>
> Subject: Re: CRAN package RItools
> On 22/07/2022 08:08, Prof Brian Ripley wrote:
>> Dear maintainer,
>>
>> Please see the problems shown on
>> <https://urldefense.com/v3/__https://cran.r-project.org/web/checks/check_results_RItools.html__;!!DZ3fjg!_ZfcFFS3tBaRO092vvaVQbmfL8lW2Z3CnHMK85z53L_SxMrNCne4wPjkI0t7AD-rnEkB0NpjuBUfLZuC8x4Se7cu$ >.
>>
>> Please correct before 2022-08-08 to safely retain your package on CRAN.
>>
>> Do remember to look at the 'Additional issues'.
>>
>> The CRAN Team
> 
> Your test obfuscation suite does not even tell us what the warnings were!
> 
> --
> Brian D. Ripley,                  [ripley@stats.ox.ac.uk](mailto:ripley@stats.ox.ac.uk)
> Emeritus Professor of Applied Statistics, University of Oxford
> 
>        [[alternative HTML version deleted]]
>

**Comment by jwbowers** [comment]
Do we have easy access to a place where we can debug this problem?

**Comment by jwbowers** [comment]
I'm currently working on this (trying to see if I can use conda on linux to do this, but it is taking a while.)

**Comment by jwbowers** [comment]
I'm closing this long issue and starting another one about ATLAS.
