### ISSUE TITLE
Two small `balanceTest` issues

### ISSUE THREAD

**Issue by markmfredrickson** [markmfredrickson/RItools#127]
In the process of working with the package, I've noticed two issues with `balanceTest`.

1. If the only outcome is constant or collinear with the stratification, the matrix inversion fails (basically a divide by zero kind of issue).
2. Factors and characters are handled differently. For factors, every level is expanded and included in the overall test. For characters, the reference level is excluded.

I will update this shortly with failing tests.

**Comment by adamrauh** [comment]
What would be a reasonable way to handle (1)?

**Comment by markmfredrickson** [comment]
> What would be a reasonable way to handle (1)?

I think we just want to give an informative error message rather than the cryptic message from LAPACK. The error message should let the user know that we can't perform a hypothesis test because the data are constant. Here's a related message from `t.test` that I think could be a little more explicit, but is there for the same reason:

```
> t.test(c(1,1,1,1,1))
Error in t.test.default(c(1, 1, 1, 1, 1)) : data are essentially constant
```

**Comment by jwbowers** [comment]
@markmfredrickson I accepted these patches into branch issue-127. It seems like issue-127 is behind main. Should we pull from main into issue-127 and then do a pull request from issue-127 into main?

**Comment by benthestatistician** [comment]
I pulled the main branch into issue-127, tweaking tests so that it passes make check locally.  I think a quick pull request makes sense, if only for a clear layout of the changes.
