### ISSUE TITLE
`balanceTest` plot, x-axis label when `absolute=TRUE`

### ISSUE THREAD

**Issue by josherrickson** [markmfredrickson/RItools#129]
By default, the x-axis label is "Standardized Differences". When the `absolute=TRUE` option is passed, the plotted points are actually absolute std dif. Any objections to modifying the x-axis label to "Absolute Standardized Differences" in this scenario? If the user passes in any custom x-axis label, we'd not make the change.

**Comment by josherrickson** [comment]
@benthestatistician @jwbowers @markmfredrickson Happy to make this change, just wanted to make sure no one had an issue with it.

**Comment by benthestatistician** [comment]
Good idea; no issue here!

**Comment by jwbowers** [comment]
No objection. Good idea. Thanks!

Jake Bowers
http://jakebowers.org
