### ISSUE TITLE
A new warning from CRAN Testing

### ISSUE THREAD

**Issue by jwbowers** [markmfredrickson/RItools#131]
Just got a message that we need to deal with a new WARNING on CRAN testing to avoid having the package pulled from CRAN: 

https://cran.r-project.org/web/checks/check_results_RItools.html

> Dear maintainer,
>Please see the problems shown on
> <https://urldefense.com/v3/__https://cran.rproject.org/web/checks/check_results_RItools.html__;!!DZ3fjg!6oP2Uvbwqd7WY6Qabot0D6TGSjoOayFSYKTr-WO81Rn_OuJVk3MMDNmIZUgSF_eRudHlTZ467vk86MCQs8k4q_ZQpAg$ >.

> Please correct before 2023-03-22 to safely retain your package on CRAN.

> Best,
> -k

**Comment by jwbowers** [comment]
The warning is:
```
checking S3 generic/method consistency ... WARNING
xtable:
  function(x, caption, label, align, digits, display, auto, ...)
xtable.xbal:
  function(x, caption, label, align, digits, display, col.labels, ...)

See section ‘Generic functions and methods’ in the ‘Writing R
Extensions’ manual.
```

**Comment by jwbowers** [comment]
The warnings are popping up for development versions of R.

**Comment by josherrickson** [comment]
It's weird that this is popping up now, given that the xtable package hasn't been updated [in years](https://cran.r-project.org/web/packages/xtable/index.html). I looked through R's NEWS briefly to see if there's anything on R-devel that makes it more strict about generics for non-base packages, but don't see anything. Need to be a bit careful in fixing; in addition to checking whether any changes addresses the warning on R-devel, need to also make sure changes don't break R-rel or R-old.

**Comment by benthestatistician** [comment]
Maybe it would be enough to add an `auto=` argument to `xtable.xbal()`, putting it before `col.labels=`.  (I.e., maybe we woudn't need to go to the trouble to get rid of the `col.labels` argument, which would maybe call for more surgery and more decisions.)  That seems unlikely to cause problems in other build checks.

**Comment by josherrickson** [comment]
Yes, that should be sufficient.

**Comment by josherrickson** [comment]
I pushed up fixes. 52e18c547aab150a9892284b976c2f0b8a6f8d8b and 2e2c8ae0f59c4723e2699f368c3d3f521094d7ba.

**Comment by jwbowers** [comment]
On CRAN now
