### ISSUE TITLE
Why would csq and thus p.value be quietly NaN?

### ISSUE THREAD

**Issue by jwbowers** [markmfredrickson/RItools#14]
With a large dataset, n=5600, 3100 treated, 2500 controls, with dim(mm)=5600, 239 (nearly all binary from factor expansion), I get:

```
xb3.wk4<-xBalance(as.formula(afmla),strata=list(unstrt=NULL,sampreg=~samp.and.region,strat=~strat), 
                  data=droplevels(ho05[abs(ho05$week)<=4,]),
                  report="chisquare.test") 

---Overall Test---
        chisquare  df p.value
unstrt        NaN 224     NaN
sampreg       199 215   0.781
strat         195 213   0.803
```

I haven't seen this behavior before.

**Comment by benthestatistician** [comment]
@jwbowers, if you have the example that generated this issue, pls keep track of it and we may look at it as work proceeds on #25.  In the meantime, closing.
