### ISSUE TITLE
`strata()` as alterative to `xBalance`'s `strata=` argument

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/RItools#15]
To dos:
- [x] Support for `strata()` within formulas
- [x] Add `strata(foo)` examples to docs
- [x] Tests
- [ ] Docs example w/ `strata(foo, bar)`

**Comment by benthestatistician** [comment]
Per  [optmatch 101](https://github.com/markmfredrickson/optmatch/issues/101) and [86](https://github.com/markmfredrickson/optmatch/issues/86) (as revised; see comment thread), it would be nice to add support for calls to `strata` on the RHS of the `xBalance` `fmla` argument:
````
xBalance(Female ~ Dept + strata(mystrat), data=UCBA)
````

I wonder, though: would this be compatible with asking for xbal calculations relevant to multiple stratifications by invoking `strata` repeatedly?  E.g., using 
````
xBalance(Female ~ Dept + strata(mystrat) + strata(yourstrat), data=UCBA)
````
to convey that I want the same thing that 
````
xBalance(Female ~ Dept, strata=UCBA[c(mystrat, yourstrat)], data=UCBA)
````
now gets you?  If so, then this could replace the current `strata` argument.

**Comment by benthestatistician** [comment]
Cross-linking w/ #30, which may be easier pickings once this can of worms has been opened. (And vice versa.)

**Comment by markmfredrickson** [comment]
If we include strata in the formula, I suggest we provide a way for users to get the unstratified balance scores. Formerly, we'd do this with `xBalance(..., strata = list("Unstratified" = NULL, "Stratified" = ~ myfactor), ...)`, which was always a little clunky. I propose we add a new argument `compute.unstratified = TRUE`. When `TRUE`, we include the unstratified balance info automatically, for both formula and explicit `strata` arguments.

Some examples
```
xBalance(z ~ x1, data = dat) # just provides unstratified results
xBalance(z ~ x1 + strata(s), data = dat) # provides both unstratified and stratified (on s) results
xBalance(z ~ x1, data = dat, compute.unstratified = FALSE) # invalid
xBalance(z ~ x1 + strata(s), data = dat, compute.unstratified = FALSE) # only computes using s
xBalance(z ~ x1, data = dat, strata = list(s = ~ s)) # longer winded version of unstratified and stratified results.
```

**Comment by benthestatistician** [comment]
Good points.

Let's do this now, but only if it doesn't add much difficulty to the
`strata` subproject as a whole.  If we can get it out soon, there'll be an
opportunity to try it in Jake's and my course.

**Comment by josherrickson** [comment]
@markmfredrickson , how would this effect the current set-up? Should `"Unadj"=NULL` be ignored in the `strata=` argument? 

Is there actually a use-case for *not* returning the unstratified version? If a user only wants a stratified version, they can extract that from the output.

Should we move away from the `strata = list('a' = a, 'b' = b)` framework altogether? If `"Unadj"=NULL` isn't needed anymore, could we just use `strata = c(a,b)` and convert it to a named list behind the scenes (so it doesn't require rewriting the actual strata engine).

**Comment by josherrickson** [comment]
This is in the master branch. Leaving this issue open for further discussion. Also, when we have more time, we should do some error- & sanity-checking on the input. Its fairy easy right now for a user to enter malformed input and receive non-sensical error messages.

**Comment by benthestatistician** [comment]
@josherrickson, you've persuaded me that this issue calls for more discussion prior to implementation.  

### Moving away from `strata = list('a'=a, 'b'=b)` framework:

+1 
Barring new objections or concerns, I'd like to depracate `xBalance`'s `strata=...` argument entirely.
The next step, actually removing the argument, will call for more confidence that we've got the various use cases covered...

### Use cases in which you don't want the unstratified comparison:    
1.  When there's a natural stratification that other stratifications of interest all subdivide.  E.g., different matches/subclassifications of schoolchildren are being considered, all made within grade level. In this case `strata(grade)` would be the base-level stratified comparison.  In terms of the current syntax, the results we want are those from ` strata = list('grade'=~grade, 'ingradematch'=~match1)`, not  ` strata = list('none'=NULL, 'grade'=~grade, 'ingradematch'=~match1)`.  (One could strip out the unstratified result later, but then you're spending time to calculate what you don't need, and effort to to avoid looking at the unneeded material alongside of the desired stuff.)
2. You're really only interested in making comparisons within a subset of the full data frame.  E.g., the data have both male and female patients, but the treatment group is all women and you only want to compare them to women.  In effect, ` strata = list('gender'=~gender, 'ingendermatch'=~match1)` achieves this, while  ` strata = list('none'=NULL, 'gender'=~gender, 'ingendermatch'=~match1)` adds on unwanted calculations and output. 

To me these favor either of these two alternatives:
A.  Accept @markmfredrickson's suggestion, to bring in a new logical arg for whether to compute the unstratified case. (This new arg might be called `compute.unstratified`, maybe something shorter and nearly as informative that I haven't thought of yet. )
B. Wrap our own version of the survival package's `strata()` function, in order to support formulas like `z~x1+x2+strata(1)+strata(mymatch)`, which would be interpreted as request for both unstratified and stratified (by `mymatch`) comparisons.  (The problem with the current `strata()` being that it doesn't recycle the vector `1` to match the length of the data.)

**Comment by markmfredrickson** [comment]
Third alternative: we could take advantage of the convention that `y ~ x1 + x2 - 1` means that the user wants to fit a regression without an intercept and use -1 to indicate to no unstratified comparison. Eg. `z ~ x1 + x2 + strata(gender) + strata(ingender) - 1` would provide the tests on `gender` and `ingender` but not on the unstratified data. 

As a consequence, `z ~ x1 - 1` would be an error as no stratification is supplied.

**Comment by benthestatistician** [comment]
+1 to Mark's 3rd alternative!

**Comment by benthestatistician** [comment]
To dos:    
1.  ` -1` in fmla as signal to exclude unstratified comparison, per @markmfredrickson 
2. Update man/xBalance.Rd, particularly examples.

**Comment by benthestatistician** [comment]
Remaining to-do's here: add tests of the usage of `strata` mentioned in my July 27 comment; update examples in man/xBalance.Rd.   (Are we using `survival:strata`, or our own or another implementation of `strata()`? I'm assuming we're using the function from the survival package, in which case `strata(ne,ct)` and similar should be taken care of for us. If that's not the case, and we don't have support for those things, OK to update documentation to exemplify what we do support and then move on.)

The `xBalance.Rd` update might also add some examples involving `cluster()`.

**Comment by benthestatistician** [comment]
Much of this functionality is present in `balanceTest()`. Closing.
