### ISSUE TITLE
New weighting, missingness handling procedures for xBalance descriptive statistics

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/RItools#36]
- Treatment group mean is treatment group mean
- adjusted mean difference and adjusted group means reflect effect-of-treatment-on-treated weighting, not harmonic
- strata contribute to adjusted difference only when there are non-missing observations in each group
- within strata, and on per-variable basis, handle missings using casewise deletion.

**Comment by markmfredrickson** [comment]
Changes made in the cluster branch. Can you verify my [ETT function](https://github.com/markmfredrickson/RItools/blob/clusters/R/harmonic.R#L5)?

**Comment by benthestatistician** [comment]
The ETT function does just what it should.

Note that since it isn't assumed that the outputs of the stratum weighting
function will sum to 1, it could even be simplified to

```{r}
effectOfTreatmentOnTreated <- function(data) {
tapply(data$Tx.grp, data$stratum.code, function(x) {
sum(x > 0)
})
}
```

or to something involving `table` as opposed to `tapply`, which may be
faster.

**Comment by benthestatistician** [comment]
Unless @markmfredrickson left this open for some specific reason that's not reflected in the comment thread, this is finished.  Thanks, Mark. Closing.
