### ISSUE TITLE
Patch Master given changes in R-devel

### ISSUE THREAD

**Issue by jwbowers** [markmfredrickson/RItools#41]
Martin Maechler emailed a patch for the RItools on CRAN given changes in R-devel (attached here zipped). I have not been able to successfully. I've asked for him to send us the tar ball itself. I figure that we would implement the changes and submit to CRAN since the other versions are not quite ready for prime time. Yes?

> A recent change of mine in R-devel (the development version of R),
> ```
> ------------------------------------------------------------------------
> r69813 | maechler | 2015-12-26 13:35:23 +0100 (Sat, 26 Dec 2015) | 1 line
> Changed paths:
>   M doc/NEWS.Rd
>   M src/main/array.c
>   M src/main/subset.c
>   M tests/reg-tests-1c.R
> 
> Array subsetting now keeps names(dim(.))
> ------------------------------------------------------------------------
> ```
> which fixes an old (but very rare) bug, has caused
> the CRAN check i.e.,  'R CMD check --as-cran  <pkg>'  checks for
> your package to fail, these are the two packages
> 
> simsalapar  and
> RItools
> 
> In both cases, the package R code made assumptions that were two
> strict and were no longer true with the current R-devel.
> As I am co-author of simsalapar,  I have already fixed the R
> code (in R-forge) and new version 1.0-8 is ready for re-submission
> by Marius (and uploaded to Winbuilder both for 'R' and
> 'R-devel', so Marius should have got Winbuilder e-mails a few
> hours ago).
> 
> For RItools  which has not been upgraded for a while, it was
> similarly easy to find the problem, and I have also updated the
> NAMESPACE (and DESCRIPTION) files to the newest "standard".
> I will send you, Jake, a tested patch file for RItools in a
> separate e-mail.

[RItools.diff.zip](https://github.com/markmfredrickson/RItools/files/75152/RItools.diff.zip)

**Comment by benthestatistician** [comment]
I'm good with this approach (ie, re-posting the Maechler-patched, old
RItools before we get around to posting any of the improvements we've been
working on).

Is it worth asking another member of our group to spend 5 min with
Maechler's patch before we give up on it?  I'm not much good with the patch
command myself, but it would be nice to be able to integrate his
suggestions into the master branch in a specific commit, without a lot of
accompanying whitespace changes and nonsense that we may end up with by
subbing in files from the tarball.

**Comment by jwbowers** [comment]
Working on this. Here is what I did.

```
$ brew install patchutils ## from https://github.com/twaugh/patchutils
$ lsdiff RItools.diff
RItools/DESCRIPTION
RItools/NAMESPACE
RItools/R/plot.xbal.R
$ filterdiff -v -i '*DESCRIPTION*' RItools.diff > DESCRIPTION.patch
$ filterdiff -v -i '*NAMESPACE*' RItools.diff > NAMESPACE.patch
$ filterdiff -v -i '*plot.xbal*' RItools.diff > plotxbal.patch
```

I patched DESCRIPTION.template by hand in  commit f78bc4055ee8156997d6857c503a538901c25d48.

I patched NAMESPACE.static by hand in commit d23d672 . **NOTE** Currently `import(abind)` shows up twice in NAMESPACE after `make package`. I don't know enough the package build process here to figure this out.

I then patched plot.xbal.R using the patching function in commit 9bd4eee . 

```
$ make package
$ mv RItools_0.1-13 RItools
$ patch -p0  --dry-run < plotxbal.patch
$ patch -p0  < plotxbal.patch
patching file RItools/R/plot.xbal.R
Hunk #3 succeeded at 272 (offset 1 line).
Hunk #4 succeeded at 282 (offset 2 lines).
Hunk #5 succeeded at 386 (offset 5 lines).
$ cp RItools/R/plot.xbal.R R/
$ make check
``

It passes make check. 

So, we need to fix the NAMESPACE file --- which has some repeated lines in it.  Then we can test master branch on R-devel, and submit. Would someone who knows about roxygen help with the NAMESPACE fix, please?

**Comment by benthestatistician** [comment]
@josherrickson is willing to take a look at the NAMESPACE duplication,
although he's unwilling to make guarantees.

If my understanding of where we are and where we're going is correct, then
this only merits a very limited investment of effort anyway.  But let me
expose my premises so that @jakebowers can correct me if I'm wrong:

**Where we are**: we can build the package into the format that CRAN
requires.  Furthermore it passes the check that CRAN will run, `R CMD check
--as-cran`. But we can't get it to this point sticking within the confines
of the Make process; we have to hand-edit the NAMESPACE en route to
building the package tarball.

**Where we're going**: We'd like to post this minor revision to the current
RItools to CRAN, then immediately switch over to working on the next
version, which embodies lots of changes including a near-total overhaul of
the Makefile.

If both of these are correct, then rather than investing effort into fixing
up our existing package compilation setup we should get comfy with the
hand-editing and move forward.

Question for @jakebowers: with the hand-editing, it passes make check.
Does it merely pass, or pass without NOTEs or WARNINGs?  If you do see
either of these, Josh, then I'd think that they merit more attention than
 relieving the need for hand editing.

**Comment by jwbowers** [comment]
I did get WARNINGS and NOTEs on R version 3.2.3 (2015-12-10): `Status: 1 WARNING, 2 NOTEs`

**Comment by jwbowers** [comment]
I'm ok with the hand-editing for now. We can even just hand edit the NAMESPACE after doing `make package` and before submitting to CRAN.  Should I just do that? (Hand-edit NAMESPACE and submit to CRAN RItools_0.1-13)

**Comment by benthestatistician** [comment]
@josherrickson, in light of @jakebowers's reply I'd like to revise the
request of you to:

1.  Investigate WARNING, see if a fix quickly occurs to you (and if so
implement it).
2. Likewise for NOTEs
3.  Edit NAMESPACE by hand or however else

In that order.  The end goal being to get it as close to WARNING and NOTE
free checking as can be done with limited investment of time. -Ben

**Comment by josherrickson** [comment]
I spent a few minutes this morning trying to fix it, unsuccessfully, so I just moved the whole package into a devtools framework. Currently, I get no WARNINGS or NOTES on either `make check` or `make build`. The whole building process is much faster as well.

It's currently on the branch "devtools." I don't spend nearly as much time here as I do in optmatch; so I'd really appreciate a second pair of eyes before I push to master, just to ensure a) I'm not missing anything obvious and b) `make document`, `make test`, `make check` and `make build` all work on a second system. (And maybe if you have time, c) play around with it for a few minutes via `make` [or `make interactive-emacs` for those of us using the One True Editor] to make sure nothing looks off, including documentation.) Once I get a confirmation that I didn't bork anything, I can merge back into master.

Note that NAMESPACE should no longer be manually edited in this framework. Changes in the Roxygen documentation (specifically `@import` and `@export` statements) can be propagated to NAMESPACE via `make document`.

**Comment by jwbowers** [comment]
I get "Status: 3 NOTEs". On my Mac.

**Comment by josherrickson** [comment]
Can you post or email me a copy of the transcript?

**Comment by jwbowers** [comment]
Only complaint seems to have to do with the .local directory.

```
* using log directory ‘/Users/jwbowers/TEMP/RItools.Rcheck’
* using R version 3.2.3 (2015-12-10)
* using platform: x86_64-apple-darwin13.4.0 (64-bit)
* using session charset: UTF-8
* checking for file ‘RItools/DESCRIPTION’ ... OK
* this is package ‘RItools’ version ‘0.1-13’
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... NOTE
Found the following hidden files and directories:
  .local
These were most likely included in error. See section ‘Package
structure’ in the ‘Writing R Extensions’ manual.
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘RItools’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of ‘data’ directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking sizes of PDF files under ‘inst/doc’ ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ... OK
  Running ‘naImputeTests.R’
  Comparing ‘naImputeTests.Rout’ to ‘naImputeTests.Rout.save’ ... OK
  Running ‘testthat.R’
  Running ‘xBalanceTests.R’
  Comparing ‘xBalanceTests.Rout’ to ‘xBalanceTests.Rout.save’ ... OK
  Running ‘xBalanceTests2.R’
  Comparing ‘xBalanceTests2.Rout’ to ‘xBalanceTests2.Rout.save’ ... OK
* checking PDF version of manual ... OK
* DONE
Status: 1 NOTE
```

**Comment by josherrickson** [comment]
Thanks Jake. I pushed an update that makes `make clean` a bit stronger and more robust (took a cue from Mark's old Makefile).

Jake, please try running `make clean` and `make check` in the devtools branch again.

**Comment by jwbowers** [comment]
Passes on OS X.

**Comment by josherrickson** [comment]
Merged into master. Should be ready to submit to CRAN.
