### ISSUE TITLE
S4 `representation` is deprecated in favor of `slots`

### ISSUE THREAD

**Issue by josherrickson** [markmfredrickson/RItools#44]
As of 3.0.0, `representation` in `setClass` is deprecated in favor of `slots`.

https://stat.ethz.ch/R-manual/R-devel/library/methods/html/setClass.html

> representation is an argument inherited from S that included both slots and contains, but the use of the latter two arguments is clearer and recommended.

https://cran.r-project.org/doc/manuals/r-release/NEWS.html

> setClass() has a new argument, slots, clearer and less ambiguous than representation. It is recommended for future code, but should be back-compatible. At the same time, the allowed slot specification is slightly more general. See the documentation for details.

**Comment by benthestatistician** [comment]
I think 4db3c5b takes care of what's left of this. Thanks @josherrickson .
