### ISSUE TITLE
Design-like objects as model frames that can be used by `lm` & similar?

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/RItools#53]
The goal being that for studies with clusters and/or strata, one and the same or closely related objects can be the basis for: 

1.  Assessment of baseline comparability, ie covariate balance, among units for which outcomes are not missing; and 
2. `lm`-based estimates, tests and confidence intervals for causal effects. 

The first goal is important in the context of education analysis, because the What Works Clearinghouse wants to see baseline comparability assessment for precisely the sample used in any given outcome analysis. 

The second is important for getting the benefits of aggregating across clusters prior to running the lm, and so that we can exercise control over the manner in which weights are dealt with.

**Comment by benthestatistician** [comment]
Does R's class structure offer some mechanism for getting an S4 object to be recognized by S3 methods as an instance of a given S3 class?  if so, then how much reorganization of the Design class would be necessary in order for `model.frame` methods to be applicable to it? I'd appreciate any advice.

A less cute alternative would be to define a coercion method to turn Design objects into model frames. 

@markmfredrickson, you'll see a relationship of this program to ideas I've been sketching out in the wiki for our cluster RCTs paper project.

**Comment by markmfredrickson** [comment]
S4 objects can have S3 methods. It just comes down to properly notating
which function is the method in the NAMESPACE file.

**Comment by benthestatistician** [comment]
Conjecture: Given a stratifying variable, clusters and/or element weights, plus any number of element and cluster level covariates and, if there were strata, stratum weights, a object storing the following would suffice for all the calcs that we expect of `xBalance`:

1.  A Treatment variable, one entry for each cluster
1. A Covariates model frame, clusters by covariates, containing cluster means of the (non-NA) values of each covariate, calculated with weighting by element weights;
3. An EWeights model frame, clusters by covariates, containing cluster sums of element weights, totaled over elements within the cluster for which the covariate in question was non-NA;
2. A VarCovariates model frame, again clusters by covariates, containing within-cluster variances along each covariate. Again these are weighted according to element weights, and again NAs are simply removed;
4. A lookup table recording the elements-to-clusters mapping; 
5. For each stratifying variable to do calculations for a lookup table recording the clusters-to-strata mapping; 
6. For each stratifying variable to do calculations for, a named numeric vector associating a weight with the stratum.

An object like this would be a first cousin to the present Design S4 object.  It would be a good bit smaller in many cases, there being no need to carry around element data.  (In an example I'm currently working with, 11K rows get collapsed down to 50 or so at the cluster level, the clusters being schools and the elements being kids within the schools.)  Only place I see us currently using element data, as opposed to means or sums of elements over clusters, is in `designToDescriptives`, where these data feed into dispersion (pooled SD's) calcs. Carrying around all that element info is a heavy price to pay for that much payoff, particularly when we could reconstitute covariate SDs from a clusters-by-covariates table, ie VarCovariates described above.  

In contrast to the present Design, the proposed requires stratum weights.  The present Design addresses a spec calling for descriptive statistics that don't require stratum weights.  Since drawing up that spec, I've come around to thinking it's better to always work from a recipe associating specific weights with each stratum, even if those weights were straightforwardly engineered to ensure that the treatment group means popping out of our Descriptives calcs coincide with means of non-NA observations in the treatment group, means calculated using element weights (if provided) but no stratum weights.  Thus, as of 9a84617 on the clusters branch, the WeightedDesign/Design distinction isn't really needed; everything could be a WeightedDesign.  

One could combine 1-4 above into a single wide data frame in which rows correspond to clusters. The distinction among these for types of columns might be recorded as attributes, along with 5-7.  With separate cleverness regarding terms objects and the like, maybe data frames like this could be a basis for model fitting on the clustered data.

**Comment by benthestatistician** [comment]
Commit 444868c7 (clusters branch) begins to address goal 1 above.  With it, if a user communicates exclusions to xBal via its subset argument, those excluded units/clusters aren't actually excluded, just downweighted to 0.  As a result, they're still factored into the design that xBal infers from the formula and data frame.  If if school A is lost to follow up and it belongs in a block w/ schools B, C, and D where random assignment was done in a balanced fashion, the user can exclude school A via subset, while B, C and D will still get inverse probability of treatment weights according to the a priori probabilities of assignment to treatment.

**Comment by benthestatistician** [comment]
Notes to self: 

1.  I'm still liking the concept of addressing point 1 (issue  statement above) via the `subset` arg of xBal, but as of this writing there's an issue with the implementation (#74). 
2. In a private repo I've got a separate proposal to address the estimation part of point 2 ([Issue 2](https://bitbucket.org/markmfredrickson/subgroup-effects-for-cluster-randomized-trials/issues/2/assignment-weights-as-an-alternative-to), "assignment weights as an alternative to stratum fixed effects"),  along with notes on addressing the tests/CIs component (of point 2 above; [Issue 5](https://bitbucket.org/markmfredrickson/subgroup-effects-for-cluster-randomized-trials/issues/5/meatrct), "meatRCT").  

If @markmfredrickson is in agreement with that other proposal then this issue is ready for closing, its component pieces being addressed in other ways (and tracked in other issues).
