### ISSUE TITLE
Imports not depends

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/RItools#56]
Per Whickham's R Packages, most of what's in our Depends field should really be in Imports:

>Now’s a good time to come back to an important issue that we glossed over earlier. What’s the difference between Depends and Imports in the DESCRIPTION ? When should you use one or the other? Listing a package in either Depends or Imports ensures that it’s installed when needed. The main difference is that where Imports just loads the package, Depends attaches it. There are no other differences. The rest of the advice in this chapter applies whether or not the package is in Depends or Imports . Unless there is a good reason otherwise, you should always list packages in Imports , not Depends . That’s because a good package is self-contained, and minimizes changes to the global environment (including the search path). The only exception is if your package is designed to be used in conjunction with another package. For example, the analogue package builds on top of vegan . It’s not useful without vegan, so it has vegan in Depends instead of Imports .

Any objections to such a change?

**Comment by josherrickson** [comment]
Most packages moved to Depends. SparseM is still in imports because I couldn't work out how to get it to work with Depends (due to using it for its class, not just functions). I suspect it's solvable, but I don't know if its worth the time at this point.

**Comment by benthestatistician** [comment]
Thanks, @josherrickson .  I agree wi/ not spending time on the special case
of SparseM.

**Comment by benthestatistician** [comment]
Re leaving SparseM in Depends, b/c we're using its classes: Did you try the `importClassesFrom` and `importMethodsFrom` directives, either in NAMESPACE directly or by appending to roxygen documentation? 

The RItools S4 class "Design" uses the SparseM  `matrix.csr` class.  Internal RItools functions that use SparseM classes and methods:

RItools function | SparseM class | SparseM method
---------------------|----------------------|------------------------
`SparseMMFromFactor` | matrix.csr | matrix.csr
`slm.fit.csr.fixed` | matrix.csr | matrix.csr

If you did try something along these lines but it turned out to be non-trivial for some reason, no reason to reopen at this time, @josherrickson -- but in that case could you record some notes about the problem while the experience is fresh?

**Comment by josherrickson** [comment]
I did try these methods.

To be more precise with the issue: If I move SparseM to Imports, and run `make interactive`, then I get (using the example from `SparseMMFromFactor`):

```{r}
> sparse_mod_matrix <-  SparseMMFromFactor(iris$Species)
> is(sparse_mod_matrix)
[1] "matrix.csr"
> s <- as.matrix(sparse_mod_matrix)
Error in as.vector(data) : 
  no method for coercing this S4 class to a vector
> library(SparseM)

Attaching package: ‘SparseM’

The following object is masked from ‘package:base’:

    backsolve

> s <- as.matrix(sparse_mod_matrix)
> dim(s)
[1] 150   3
```

The same error occurs with `importClassesFrom` and `import`. The issue is that R allows us to create a `matrix.csr` class object without SparseM loaded, but it doesn't connect it with SparseM's functions.

I don't fully understand the distinction between Depends and Imports. Here, I've started again with a fresh `make interactive` with SparseM in Imports:

```{r}
> methods(class="matrix.csr")
 [1] [          [<-        %*%        as         cbind      coerce    
 [7] dim        initialize is         kronecker  Ops        rbind     
see '?methods' for accessing help and source code
> library(SparseM)

Attaching package: ‘SparseM’

The following object is masked from ‘package:base’:

    backsolve

> methods(class="matrix.csr")
 [1] [             [<-           %*%           as.matrix     as.matrix.coo
 [6] as.matrix.csc as            as.matrix.ssc as.matrix.ssr cbind        
[11] chol          coerce        diag          diag<-        diff         
[16] dim           image         initialize    is            kronecker    
[21] norm          Ops           rbind         solve         t            
see '?methods' for accessing help and source code
```

If I move SparseM to Depends, then I get the full set of functions. I don't know why that subset exists when SparseM is in Imports.

**Comment by benthestatistician** [comment]
thanks J! Given all this, let's keep this one closed.

Re your query about Depends vs Imports: in R Packages, Namespace chapter,
Wickham says that the only distinction between the two is in whether the
package gets attached to the search path.  Perhaps your example shows that
that he somewhat oversimplifies the matter.
