### ISSUE TITLE
PPS sampling option for clusters

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/RItools#57]

**Comment by benthestatistician** [comment]
As of this writing, `xBalance` with clusters implicitly assumes that assignment probabilities are constant across clusters within a stratum.  Some natural ways of picking clusters lead to non-constant probabilities.  For example, one cluster is chosen with probability proportional to size, by selecting one individual (from among all individuals being clustered within a given stratum): then each cluster's probability of assignment to treatment is proportional to the size of the cluster.

(If more than one cluster is being assigned to treatment within a given stratum, then it's no simple task to design a probability proportional to size random selection scheme.  Schemes that people may think of as pps aren't.  How to design for this?  Perhaps the goal shouldn't be to accommodate PPS selection into treatment so much as arbitrary treatment assignment probabilities, designated or communicated in some way or another.)

**Comment by markmfredrickson** [comment]
Could this be boiled down to the probabilities that for subjects i and j,
P(Z_i = 1), P(Z_i = 1, Z_j = 1), P(Z_i = 1, Z_j = 0)? (One n-vector and two
n by n matrices).

For independent sampling, the matrices would just be products of the
marginal vector.

For n-choose-k samples, the margin would be k/n and P(Z_i = 1, Z_j = 1)  =
P(Z_i = 1)P(Z_j = 1 | Z_i = 1) = k/n ((k-1)/(n - 1)).

For clustered sampling, the mariginal probability would be constant
#{treated clusters} / #{clusters}, but the joint probabilities would be
P(Z_i = 1, Z_j = 1) = P(Z_i = 1) if i and j are in the same cluster and
P(Z_i = 1,  Z_j = 0) = 0. (And similar relationships as the n-choose-k
situation across clusters).

PPS would have cluster specific probabilities in the marginal vector and
the same joint matrices as in the general clustered case.

Would this be sufficient to compute the necessary moments of the test
statistic?
​

**Comment by benthestatistician** [comment]
I had been thinking along much the same lines as @markmfredrickson, in his last comment -- I do think we'd be able to handle just about every weighted sampling scheme by carrying inclusion probabilities and first order joint inclusion probabilities, as he suggests -- but then I got to thinking that maybe we can handle a whole bunch of PPS cluster sampling schemes, and a number of other types of situation we'd like to handle as well, with something that's probably easier to implement and write into the API.

Specifically, as an alternative to StrataMatrix/StrataFrame we might enable an "AssignmentProbability" slot, which would carry probabilities of inclusion in the treatment group. These probabilities would be assumed to be independent of one another.  For future-proofing, one might add an optional slot for joint inclusion probabilties.  (Probably would mean making the current Design class an extension of a narrower Design class, which could alternatively be extended to have AssignmentProbability rather than Strata* slots.  Another argument for adjusting/elaborating the Design class in this way: eventually we may want to use it to encode setups with more than one "instrument", i.e. treatment assignment variable.)

Many of the proportional-to-size sampling schemes that are used in sampling don't use independent sampling, and are rather elaborate.  However, my sense is that:

1.  Sampling people wind up expending quite a bit of effort on sampling in such a way as to pre-engineer precisely how many clusters (more generally, _assignment units_) will be selected.  Unclear that anyone will go to those lengths in social or medical experimentation.
2. If one is willing to give precisely control over the size (in terms of clusters) of the treatment group, then it works just fine to do an independent coin toss separately for each assignment unit. You adjust the assignment probabilities separately for each unit, in this way controlling the expected number of units assigned to treatment, and then you live with some sample-to-sample fluctuation in the outcome. 
3. A lot of social experiments do involve independent selection into the treatment condition.  E.g., admission lotteries for charter schools.
