### ISSUE TITLE
post.alignment.transformation= w/ unit weights or clusters

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/RItools#64]

**Comment by benthestatistician** [comment]
This will require a new `aggregateDesigns` alternative or  method, applicable to the objects we're using to store aligned covariates (provisionally named "AlignedCovs").

**Comment by benthestatistician** [comment]
To support the combination of aligned rank testing with element-level weights, one would have to apply a weighted rank function rather than `rank()`.  Or, use a version of `ecdf()` that accepts weights. The [bigvis package](https://github.com/hadley/bigvis) has a weighted edcf, while Hmisc has `wtd.rank()`. Of course this is just for examples. 

If we adjusted things to expect a post alignment transform function operating on matrices rather than vectors, then this could be a vehicle for more elaborate missing data handling -- or at least a vignette demonstration of how to set such a thing up after studying a missingness pattern.

**Comment by benthestatistician** [comment]
Is anyone aware of users who make use of `xBalance()`'s `post.alignment.transform` argument?  (Outside of our EE project, I mean.)  If not, and maybe even if so, I'm inclined to abandon that functionality in `balanceTest()`.   

Supporting it is standing in the way of progress on other fronts.  In particular, but for the need to implement such a transform, we could do away with `alignDesignsByStrata()` by executing the limited amount of alignment that's necessary from within `alignedToInferentials()`. This would save time and memory, improve alignment between the codebase and the H. & B. _Statistical Science_ paper, and simplify a fix of some lingering irritations noted in comments to #89.

I think we could roll this functionality back in such a way that we ourselves can still produce it when needed, by rolling our own alternative to `balanceTest()` that makes uses of its subroutines in particular ways.  If there are also other power users out there who like the functionality, maybe we could export a few of these subroutines and offer a vignette demonstrating how to make it all go. 

@jwbowers @markmfredrickson @josherrickson

**Comment by jwbowers** [comment]
Hi All, I am ok with removing it. I think the idea of rank transforms or
other robust transforms have been attractive, but I wonder how hard it
would be to just make those more or less hard coded? Or put them on the
back burner?

Jake Bowers
http://jakebowers.org

**Comment by benthestatistician** [comment]
As an easier-to-implement alternative to performing these transformations prior to aggregation within a cluster, we might stipulate that a post.alignment.transformation has to accept a `weights=`, `weight=` or `w=`  argument. W/ corresponding updates to examples.   

```r
library(Hmisc)
x = matrix(1:9,3,3)
apply(x, 2, wtd.rank, w=rep(1,3))
```
