### ISSUE TITLE
ERRORS in Web Checks

### ISSUE THREAD

**Issue by jwbowers** [markmfredrickson/RItools#70]
Hi All,

In working to do `devtools::release()` on the fixed version, I ran into ERRORs here:

https://cran.rstudio.com/web/checks/check_results_RItools.html

I don't understand them and don't have access to Windows.

Any hints?

Jake

**Comment by josherrickson** [comment]
None of them seem that urgent - RSVGTipsDevice is often not available on headless servers, and the Optmatch error could have come up during the day when it was offline. The testing error I have no idea, but there's absolutely no useful information there about it.

If the `devtools::build_win()` results didn't include these (or at least, nothing beyond the RSVGTipsDevice), I'd vote to ignore it

**Comment by josherrickson** [comment]
I started a run yesterday on winbuilder, and it didn't finish till this morning apparently. Results for the next 72 hours are here: http://win-builder.r-project.org/h6nvQXBPPgEi/

Only relevant error was:

```
Found the following (possibly) invalid URLs:
  URL: http://www.jakebowers.org/RItools.html
    From: inst/CITATION
    Status: Error
    Message: libcurl error code 52
    	Empty reply from server
```

**Comment by jwbowers** [comment]
Ok. Submitted it. I'll close this issue and open another one if we have trouble.
