### ISSUE TITLE
should `xBalance` warn when dropping subclasses due to lack of variation in tx var?

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/RItools#73]
In a project where I'm testing a sequence of designs, I'm seeing warnings like

>  Warning in makeDesigns(fmla, data): Dropped 519 levels of
>   strata(arr250.3cat, popcat, DIV2, year) which did not include both treated
>   and control units

In this particular context, the warnings is distracting. E.g., not clear why I should be concerned about the specific number of levels dropped.  

Maybe this warning should be removed. Or shortened and adjusted.  Maybe there should be an explicit option to suppress it, e.g. in PDF or HTML output.  Not immediately clear how this context differs, if at all, from the one we had in mind when we wrote the warning. Things to consider/discuss....

**Comment by markmfredrickson** [comment]
Just to be clear, in this context, "levels" is matched sets. In general, I think this falls under the category of it's better to flag deletions than to do it silently. 

I'd prefer to have this set via an `options` call, just to keep the function signature from getting too verbose.

**Comment by benthestatistician** [comment]
In the project I was referring to, the levels being dropped weren't matched sets, just levels of a factor variable -- I was doing a form of coarsened exact matching.  In the specific case of matched sets I'd agree with you about a preference to flag; in this alternate usage case, however, I would have preferred to forgo the flags.

**Comment by benthestatistician** [comment]
I can live w/ the behavior I was worried about in this issue. Closing.
