### ISSUE TITLE
adjust `xBalance`'s data frame construction to grab vars that only appear in `I()` terms`

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/RItools#76]
Although this works,
```{r}
 lm(treat~I(mr04*pop06)+I(mr05*pop06),data=mass.study)
```
this doesn't:
```{r}
xBalance(treat~I(mr04*pop06)+I(mr05*pop06),data=mass.study,report='all')
Error in unique(c("AsIs", oldClass(x))) : object 'mr04' not found
```
Not sure why, maybe it would be easy to fix. (This using `xBal` from [clusters fb7c57f9] )

**Comment by markmfredrickson** [comment]
The issue appears to be that we call `model.frame` twice. Once in `makeDesigns` and then `makeDesigns` calls it on `design_matrix`. 

It is easy to eliminate the first call to `model.frame` and rely on `design_matrix` to make this call, but it becomes a little tricky the get the factor expansion we want for `xBalance`. 

My suggestion is to remove the call to `model.frame` in `design_matrix` to make it more closely parallel `model.matrix`. But before I implement this, I thought I'd check in to see if this would be a particularly bad idea.

**Comment by benthestatistician** [comment]
I think I recall my original plan for `design_matrix` being as you suggest, but then `model.frame` crept its way in in the process of making things go.  I would probably have left tests for whatever it was that was tripping me up, though, so feel free to see if you can get it going without the second `model.frame` call.

**Comment by markmfredrickson** [comment]
The big fall out from the change was the need to call `model.frame` in the tests, but easy to do. Closing.

**Comment by benthestatistician** [comment]
Thanks!  :+1:
