### ISSUE TITLE
master version number

### ISSUE THREAD

**Issue by josherrickson** [markmfredrickson/RItools#78]
This is an entirely self-serving issue.

0.1-15 is the most recent version on CRAN, based on the issue71 branch. Master is still flagged as 0.1-14. I have master built & installed locally for some work. When running `update.packages()`, since the version on CRAN is "newer" than master, it attempts to overwrite it. (and I always forget to tell it not to...)

Any reason not to bump master a new version? Perhaps 0.1-15.9000 (per [Hadley](http://r-pkgs.had.co.nz/description.html#version)) or even 0.1-16?

If there's a reason I'm not seeing for keeping master at 0.1-14, feel free to ignore this.

**Comment by benthestatistician** [comment]
I vote to bump master to 0.2-0.

**Comment by jwbowers** [comment]
Sounds good.

**Comment by josherrickson** [comment]
Thanks. Closing.
