### ISSUE TITLE
`with_libpaths` instead of `.libPaths()` in README.txt install instructions?

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/RItools#79]
`.libPaths()` has a habit of forgetting library paths when you try to add another one.  This leads to   weird errors that are hard to figure out:

```{r}
> library('devtools')
> .libPaths('lib')
> install_github("markmfredrickson/RItools")
Error in loadNamespace(name) : there is no package called ‘httr’
> .libPaths()
[1] "/Users/bbh/Dropbox/Documents/teach/gradCI/working/lib"         
[2] "/Library/Frameworks/R.framework/Versions/3.3/Resources/library"
```

How about we use `withr::with_libpaths` instead?

```{r}
> library('devtools')
> library('withr')


Attaching package: ‘withr’

The following objects are masked from ‘package:devtools’:

    with_collate, with_envvar, with_libpaths, with_locale,
    with_makevars, with_options, with_par, with_path


> with_libpaths("./lib", install_github("markmfredrickson/RItools"))
Error in loadNamespace(name) : there is no package called ‘httr’
> with_libpaths("./lib", install_github("markmfredrickson/RItools"), 'pre')
Downloading GitHub repo markmfredrickson/RItools@master
```

open to other alternatives....

**Comment by josherrickson** [comment]
Is there any reason to avoid telling people to reinstall? Something like

> To install the development version, use
> ``` 
> devtools::install_github("markmfredrickson/RItools")
> ```
>
> or, to install the `randomization-distribution` branch,
>
> ``` 
> devtools::install_github("markmfredrickson/RItools@randomization-distribution")
> ```
>
> To switch back to the version maintained on CRAN, simply run
> ```
> install.packages("RItools")
> ```

I've always thought that libpath bit was unnecessarily complicate.d

**Comment by benthestatistician** [comment]
My own pref goes in the other direction from @josherrickson's -- it seems to me like a best practice to avoid leaving bleeding-edge, unreleased software sitting around on one's system to cause confusion later.   Best practice for everyone, but especially for newbies who may not be aware that they may be creating weird traps for themselves months or years in the future, when it looks to them like they've got the same version 0.2, say, that was later posted on CRAN, but in fact they've got a development version that preceded that one. We can also do a better job of handling bug reports if we present this sort of thing.

From this perspective it seems to me more like we should be recommending something like `p_temp` from the [pacman package](https://github.com/trinker/pacman).  I haven't used that package yet myself, however -- anybody w/ relevant experience do pipe up.

**Comment by josherrickson** [comment]
`p_temp` looks promising, though a bit burdensome for a user to have to install it everytime.

devtools' (`dev-mode`)[http://www.inside-r.org/packages/cran/devtools/docs/dev_mode] seems very nice. In fact, I'm going to start using it myself. What about something like this?

> We recommend using `devtools::dev_mode()` to install the development branch of RItools. To use it,
> 
> ```
> > devtools::dev_mode() # run again to de-activate
> d> devtools::install_github("markmfredrickson/RItools")
> d> library(RItools)
> ```
> 
> To activate the CRAN version, simply load RItools without activating `dev-mode`
> 
> ```
> > library(devtools)
> ```
>

**Comment by benthestatistician** [comment]
:+1:

Could you add a sentence or so to explain to people what the effect of `dev_mode()` is?

**Comment by josherrickson** [comment]
README updated. I'll update optmatch while I'm at it.
